//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLEdotNET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLEdotNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] _default {
            get {
                object obj = ResourceManager.GetObject("_default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _default1 {
            get {
                object obj = ResourceManager.GetObject("_default1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_16x16 {
            get {
                object obj = ResourceManager.GetObject("add_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addcube {
            get {
                object obj = ResourceManager.GetObject("addcube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addyndlight {
            get {
                object obj = ResourceManager.GetObject("addyndlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] alien1 {
            get {
                object obj = ResourceManager.GetObject("alien1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] alien11 {
            get {
                object obj = ResourceManager.GetObject("alien11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] alien2 {
            get {
                object obj = ResourceManager.GetObject("alien2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] alien21 {
            get {
                object obj = ResourceManager.GetObject("alien21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap align_16x16 {
            get {
                object obj = ResourceManager.GetObject("align_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignall {
            get {
                object obj = ResourceManager.GetObject("alignall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignall_16x16 {
            get {
                object obj = ResourceManager.GetObject("alignall_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignchildren {
            get {
                object obj = ResourceManager.GetObject("alignchildren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aligndown {
            get {
                object obj = ResourceManager.GetObject("aligndown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignup {
            get {
                object obj = ResourceManager.GetObject("alignup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blockmode {
            get {
                object obj = ResourceManager.GetObject("blockmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blockmode_16x16 {
            get {
                object obj = ResourceManager.GetObject("blockmode_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brokenwall_16x16 {
            get {
                object obj = ResourceManager.GetObject("brokenwall_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chainwheel_16x16 {
            get {
                object obj = ResourceManager.GetObject("chainwheel_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkmine {
            get {
                object obj = ResourceManager.GetObject("checkmine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_16x16 {
            get {
                object obj = ResourceManager.GetObject("copy_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] credits {
            get {
                object obj = ResourceManager.GetObject("credits", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] credits1 {
            get {
                object obj = ResourceManager.GetObject("credits1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cubemode {
            get {
                object obj = ResourceManager.GetObject("cubemode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cubetool {
            get {
                object obj = ResourceManager.GetObject("cubetool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut_16x16 {
            get {
                object obj = ResourceManager.GetObject("cut_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] d12d2 {
            get {
                object obj = ResourceManager.GetObject("d12d2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deldynlight {
            get {
                object obj = ResourceManager.GetObject("deldynlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] descent {
            get {
                object obj = ResourceManager.GetObject("descent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] descent1 {
            get {
                object obj = ResourceManager.GetObject("descent1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] descent2 {
            get {
                object obj = ResourceManager.GetObject("descent2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] descent21 {
            get {
                object obj = ResourceManager.GetObject("descent21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap diagnosis_16x16 {
            get {
                object obj = ResourceManager.GetObject("diagnosis_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] drag {
            get {
                object obj = ResourceManager.GetObject("drag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap effecttool_16x16 {
            get {
                object obj = ResourceManager.GetObject("effecttool_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expand_16x16 {
            get {
                object obj = ResourceManager.GetObject("expand_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expandhorz_16x16 {
            get {
                object obj = ResourceManager.GetObject("expandhorz_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expandvert_16x16 {
            get {
                object obj = ResourceManager.GetObject("expandvert_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap extendcube {
            get {
                object obj = ResourceManager.GetObject("extendcube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] fire {
            get {
                object obj = ResourceManager.GetObject("fire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fire1 {
            get {
                object obj = ResourceManager.GetObject("fire1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fitview {
            get {
                object obj = ResourceManager.GetObject("fitview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fliphorz_16x16 {
            get {
                object obj = ResourceManager.GetObject("fliphorz_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flipvert_16x16 {
            get {
                object obj = ResourceManager.GetObject("flipvert_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fullscreen {
            get {
                object obj = ResourceManager.GetObject("fullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] groupa {
            get {
                object obj = ResourceManager.GetObject("groupa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] groupa1 {
            get {
                object obj = ResourceManager.GetObject("groupa1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap horzflip {
            get {
                object obj = ResourceManager.GetObject("horzflip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ice {
            get {
                object obj = ResourceManager.GetObject("ice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ice1 {
            get {
                object obj = ResourceManager.GetObject("ice1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap joinlines {
            get {
                object obj = ResourceManager.GetObject("joinlines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap joinlines_16x16 {
            get {
                object obj = ResourceManager.GetObject("joinlines_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap joinpoints {
            get {
                object obj = ResourceManager.GetObject("joinpoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap joinpoints_16x16 {
            get {
                object obj = ResourceManager.GetObject("joinpoints_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap joinsides {
            get {
                object obj = ResourceManager.GetObject("joinsides", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap joinsides_16x16 {
            get {
                object obj = ResourceManager.GetObject("joinsides_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] level1 {
            get {
                object obj = ResourceManager.GetObject("level1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] level1b {
            get {
                object obj = ResourceManager.GetObject("level1b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] level1c {
            get {
                object obj = ResourceManager.GetObject("level1c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] level1d {
            get {
                object obj = ResourceManager.GetObject("level1d", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] level1e {
            get {
                object obj = ResourceManager.GetObject("level1e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] level1f {
            get {
                object obj = ResourceManager.GetObject("level1f", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] light {
            get {
                object obj = ResourceManager.GetObject("light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] light2 {
            get {
                object obj = ResourceManager.GetObject("light2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightbulb_16x16 {
            get {
                object obj = ResourceManager.GetObject("lightbulb_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lighttool {
            get {
                object obj = ResourceManager.GetObject("lighttool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lighttool_16x16 {
            get {
                object obj = ResourceManager.GetObject("lighttool_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_16x16 {
            get {
                object obj = ResourceManager.GetObject("line_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap linemode {
            get {
                object obj = ResourceManager.GetObject("linemode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mirrorcube {
            get {
                object obj = ResourceManager.GetObject("mirrorcube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap missiontool_16x16 {
            get {
                object obj = ResourceManager.GetObject("missiontool_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap movedown {
            get {
                object obj = ResourceManager.GetObject("movedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap movedown_16x16 {
            get {
                object obj = ResourceManager.GetObject("movedown_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moveleft {
            get {
                object obj = ResourceManager.GetObject("moveleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moveleft_16x16 {
            get {
                object obj = ResourceManager.GetObject("moveleft_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moveright {
            get {
                object obj = ResourceManager.GetObject("moveright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moveright_16x16 {
            get {
                object obj = ResourceManager.GetObject("moveright_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moveup {
            get {
                object obj = ResourceManager.GetObject("moveup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moveup_16x16 {
            get {
                object obj = ResourceManager.GetObject("moveup_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] new_save {
            get {
                object obj = ResourceManager.GetObject("new_save", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] new_save1 {
            get {
                object obj = ResourceManager.GetObject("new_save1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] new_save2 {
            get {
                object obj = ResourceManager.GetObject("new_save2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] new_save3 {
            get {
                object obj = ResourceManager.GetObject("new_save3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] new1 {
            get {
                object obj = ResourceManager.GetObject("new1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] new2 {
            get {
                object obj = ResourceManager.GetObject("new2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] new3 {
            get {
                object obj = ResourceManager.GetObject("new3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nozoom_16x16 {
            get {
                object obj = ResourceManager.GetObject("nozoom_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objectmode {
            get {
                object obj = ResourceManager.GetObject("objectmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objects_16x16 {
            get {
                object obj = ResourceManager.GetObject("objects_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap objecttool {
            get {
                object obj = ResourceManager.GetObject("objecttool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openfile_16x16 {
            get {
                object obj = ResourceManager.GetObject("openfile_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] palette {
            get {
                object obj = ResourceManager.GetObject("palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] palette1 {
            get {
                object obj = ResourceManager.GetObject("palette1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pan {
            get {
                object obj = ResourceManager.GetObject("pan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste_16x16 {
            get {
                object obj = ResourceManager.GetObject("paste_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pofs1 {
            get {
                object obj = ResourceManager.GetObject("pofs1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pofs2 {
            get {
                object obj = ResourceManager.GetObject("pofs2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap point_16x16 {
            get {
                object obj = ResourceManager.GetObject("point_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pointmode {
            get {
                object obj = ResourceManager.GetObject("pointmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preferences {
            get {
                object obj = ResourceManager.GetObject("preferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] rc_data1 {
            get {
                object obj = ResourceManager.GetObject("rc_data1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reactor_16x16 {
            get {
                object obj = ResourceManager.GetObject("reactor_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo_16x16 {
            get {
                object obj = ResourceManager.GetObject("redo_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redraw {
            get {
                object obj = ResourceManager.GetObject("redraw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16x16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resetaligment {
            get {
                object obj = ResourceManager.GetObject("resetaligment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resetblue_16x16 {
            get {
                object obj = ResourceManager.GetObject("resetblue_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resetmarked {
            get {
                object obj = ResourceManager.GetObject("resetmarked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resetred_16x16 {
            get {
                object obj = ResourceManager.GetObject("resetred_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] robot {
            get {
                object obj = ResourceManager.GetObject("robot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rotate {
            get {
                object obj = ResourceManager.GetObject("rotate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap savefile {
            get {
                object obj = ResourceManager.GetObject("savefile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap savefile_16x16 {
            get {
                object obj = ResourceManager.GetObject("savefile_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap segment_16x16 {
            get {
                object obj = ResourceManager.GetObject("segment_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap segments_16x16 {
            get {
                object obj = ResourceManager.GetObject("segments_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap segmenttool_16x16 {
            get {
                object obj = ResourceManager.GetObject("segmenttool_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings_16x16 {
            get {
                object obj = ResourceManager.GetObject("settings_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ship {
            get {
                object obj = ResourceManager.GetObject("ship", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shrinkhorz {
            get {
                object obj = ResourceManager.GetObject("shrinkhorz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shrinkvert {
            get {
                object obj = ResourceManager.GetObject("shrinkvert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sidemode {
            get {
                object obj = ResourceManager.GetObject("sidemode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sides_16x16 {
            get {
                object obj = ResourceManager.GetObject("sides_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splitlines {
            get {
                object obj = ResourceManager.GetObject("splitlines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splitlines_16x16 {
            get {
                object obj = ResourceManager.GetObject("splitlines_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splitpoints {
            get {
                object obj = ResourceManager.GetObject("splitpoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splitpoints_16x16 {
            get {
                object obj = ResourceManager.GetObject("splitpoints_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splitscreen {
            get {
                object obj = ResourceManager.GetObject("splitscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splitsides {
            get {
                object obj = ResourceManager.GetObject("splitsides", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splitsides_16x16 {
            get {
                object obj = ResourceManager.GetObject("splitsides_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stretchtofit {
            get {
                object obj = ResourceManager.GetObject("stretchtofit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap subtract_16x16 {
            get {
                object obj = ResourceManager.GetObject("subtract_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] temp {
            get {
                object obj = ResourceManager.GetObject("temp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] temp2 {
            get {
                object obj = ResourceManager.GetObject("temp2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] temp21 {
            get {
                object obj = ResourceManager.GetObject("temp21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] texture {
            get {
                object obj = ResourceManager.GetObject("texture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] texture2 {
            get {
                object obj = ResourceManager.GetObject("texture2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texturefilter_16x16 {
            get {
                object obj = ResourceManager.GetObject("texturefilter_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texturetool {
            get {
                object obj = ResourceManager.GetObject("texturetool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texturetool_16x16 {
            get {
                object obj = ResourceManager.GetObject("texturetool_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] tnames {
            get {
                object obj = ResourceManager.GetObject("tnames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tnames2 {
            get {
                object obj = ResourceManager.GetObject("tnames2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap truecolor_16x16 {
            get {
                object obj = ResourceManager.GetObject("truecolor_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap truecolor_32x32 {
            get {
                object obj = ResourceManager.GetObject("truecolor_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo_16x16 {
            get {
                object obj = ResourceManager.GetObject("undo_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walltool {
            get {
                object obj = ResourceManager.GetObject("walltool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] water {
            get {
                object obj = ResourceManager.GetObject("water", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] water1 {
            get {
                object obj = ResourceManager.GetObject("water1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xhairs {
            get {
                object obj = ResourceManager.GetObject("xhairs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xrotleft {
            get {
                object obj = ResourceManager.GetObject("xrotleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xrotleft_16x16 {
            get {
                object obj = ResourceManager.GetObject("xrotleft_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xrotright {
            get {
                object obj = ResourceManager.GetObject("xrotright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xrotright_16x16 {
            get {
                object obj = ResourceManager.GetObject("xrotright_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yrotleft {
            get {
                object obj = ResourceManager.GetObject("yrotleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yrotleft_16x16 {
            get {
                object obj = ResourceManager.GetObject("yrotleft_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yrotright {
            get {
                object obj = ResourceManager.GetObject("yrotright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yrotright_16x16 {
            get {
                object obj = ResourceManager.GetObject("yrotright_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoomin {
            get {
                object obj = ResourceManager.GetObject("zoomin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoomin_16x16 {
            get {
                object obj = ResourceManager.GetObject("zoomin_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] zoomin1 {
            get {
                object obj = ResourceManager.GetObject("zoomin1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoomout {
            get {
                object obj = ResourceManager.GetObject("zoomout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoomout_16x16 {
            get {
                object obj = ResourceManager.GetObject("zoomout_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] zoomout1 {
            get {
                object obj = ResourceManager.GetObject("zoomout1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zrotleft {
            get {
                object obj = ResourceManager.GetObject("zrotleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zrotleft_16x16 {
            get {
                object obj = ResourceManager.GetObject("zrotleft_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zrotright {
            get {
                object obj = ResourceManager.GetObject("zrotright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zrotright_16x16 {
            get {
                object obj = ResourceManager.GetObject("zrotright_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
